name: Java CI with Maven - Test and package

# Ce workflow s'exécute lors d'une pull request vers la branche main
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Récupérer le dépôt avec l'action actions/checkout@v4
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2: Configurer Java avec l'action actions/setup-java@v4 (version 21 de Corretto)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Étape 3: Compiler et tester le projet avec Maven
      - name: Build with Maven
        run: mvn -B package
