name: Java CI with Maven - Test and package

# Ce workflow s'exécute lors d'une pull request vers la branche main
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest # ou s'exécute le job

    steps:
      # Étape 1: Récupérer le dépôt avec l'action actions/checkout@v4
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2: Configurer Java avec l'action actions/setup-java@v4 (version 21 de Corretto)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarqube-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
             ${{ runner.os }}-sonarqube-


      # Étape 3: Compiler et tester le projet avec Maven
      - name: Build with Maven
        run: mvn -B package

      - name: Build with Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')





